function net=add_conv(net, dim, lrs, stride, pad, nnz)
    type = 'single';
    weight = init_weight('xavierimproved',dim(1),dim(2),dim(3),dim(4), type);
    
    net.layers{end+1} = struct(...
       'type', 'conv', ...
       'weights', {{weight, zeros(1, dim(4), type)}}, ...
       'learningRate', lrs, ...
       'stride', stride, ...
       'pad', pad);
end
