function net=add_pool(net, type, dim, stride, pad)
    net.layers{end+1} = struct(...
       'type', 'pool', ...
       'method', type, ...
       'pool', dim, ...
       'stride', stride, ...
       'pad', pad) ;
end